version: "3.7"
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/mysql
    # env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    command: '--default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp'
    network_mode: bridge

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
    ports:
      - 3306:80
    volumes:
      - ./sessions:/sessions
    network_mode: bridge
    depends_on:
      - mysql
    external_links:
      - mysql
