version: "3"
services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      # MYSQL_USER: $MYSQL_USER
      # MYSQL_PASSWORD: $MYSQL_PASSWORD
      # MYSQL_DATABASE: $MYSQL_DATABASE
    command: '--default-authentication-plugin=mysql_native_password'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 3306:80
    # environment:
    #   PMA_HOST: localhost
    volumes:
      - ./sessions:/sessions
    external_links:
      - db
